### ISSUE TITLE
super slow and corrupted download

### ISSUE THREAD

**Issue by zaibon** [gigforks/minio#26]
Build using : ed0a0d2f4f4e93e9a74f54a134e91de236a4926d

Uploading files works ok, but when trying to download the files back, it takes a long time before the download actually starts and then the file is corrupted. Most of the time I only get a few first KiB of the file.

0-stor config used
```
namespace: miniotest
password: None
datastor: # required
  shards: # required
    - 172.20.0.91:9900
    - 172.20.0.91:9901
    - 172.20.0.91:9902
    - 172.20.0.91:9903
    - 172.20.0.91:9904
    - 172.20.0.91:9905
    - 172.20.0.91:9906
    - 172.20.0.92:9900
    - 172.20.0.92:9901
    - 172.20.0.92:9902
    - 172.20.0.92:9903
    - 172.20.0.92:9904
    - 172.20.0.92:9905
    - 172.20.0.92:9906
  pipeline:
    block_size: 1049000
    compression: # optional, snappy by default
      type: snappy # snappy is the default, other options: lz4, gzip
      mode: default # default is the default, other options: best_speed, best_compression
    encryption: # optional, disabled by default
      type: aes # aes is the default and only standard option
      private_key: ab345678901234567890123456789012
```

**Comment by zaibon** [comment]
```
Trace: 1: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/object-handlers.go:172:cmd.objectAPIHandlers.GetObjectHandler()
       2: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/api-router.go:59:cmd.(objectAPIHandlers).GetObjectHandler-fm()
       3: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
       4: /home/zaibon/dev/go/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
       5: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:563:cmd.pathValidityHandler.ServeHTTP()
       6: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
       7: :0:()
       8: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
       9: :0:()
      10: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:219:cmd.redirectHandler.ServeHTTP()
      11: :0:()
      12: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:277:cmd.minioReservedBucketHandler.ServeHTTP()
      13: :0:()
      14: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:246:cmd.cacheControlHandler.ServeHTTP()
      15: :0:()
      16: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:347:cmd.timeValidityHandler.ServeHTTP()
      17: :0:()
      18: /home/zaibon/dev/go/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      19: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      20: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      21: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/generic-handlers.go:453:cmd.resourceHandler.ServeHTTP()
      22: /home/zaibon/dev/go/src/github.com/minio/minio/cmd/auth-handler.go:245:cmd.authHandler.ServeHTTP()
      23: :0:()
      24: /home/zaibon/dev/go/src/github.com/minio/minio/pkg/http/server.go:111:http.(*Server).Start.func1()
      25: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      26: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      27: net/http/server.go:2694:http.serverHandler.ServeHTTP()
      28: net/http/server.go:1830:http.(*conn).serve()
[2018-03-14T14:53:39.576127801Z] [ERROR] Unable to write to client. (read tcp 172.18.0.10:39428->172.20.0.91:9905: i/o timeout)
```

Seems after a while the download fails due to a timeout. I got that trying to download a file of 2MiB +- so that should be fast

**Comment by iwanbk** [comment]
Tried it with my config with only two shards, it works fine.

Start with empty files and then create the bucket
```
$ mc ls myzerostor                                                                                                 
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ mc mb myzerostor/bening
Bucket created successfully `myzerostor/bening`.
```

Then upload 24M of file, `minio` binary
```
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ ls /tmp/minio -lh                                                                                                
-rwxrwxr-x 1 ibk ibk 24M Mar 15 09:11 /tmp/minio
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ mc cp /tmp/minio myzerostor/bening/                                                                              
/tmp/minio:          23.46 MB / 23.46 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 14.98 MB/s 1sibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
```
Download that file and `cmp` it to check
```
$ mc cat myzerostor/bening/minio > /tmp/down                                                                       
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ cmp /tmp/minio /tmp/down 
ibk@siputih:~/pathgo/src/github.com/minio/minio/cmd/gateway/zerostor
$ mc ls myzerostor/bening
[2018-03-15 09:22:02 WIB]  24MiB minio
```

i'll try to mimic your config

**Comment by iwanbk** [comment]
> i'll try to mimic your config

tested with same config, except only use 7 shards, it still works fine.

Have you checked 0-db side, make sure you didn't get https://github.com/rivine/0-db/issues/20.

**Comment by iwanbk** [comment]
More tests by me & @zaibon : 
- local test was fine
- minio & 0-db in internet, `mc` in local was fine

seems like 0-os related issue.

I've added some debugging message to #27.
Need to set `MINIO_ZEROSTOR_DEBUG` env variable to `1`

If it previously work with 0-os, the only part changed was 0-stor `ReadRange` addition.
We can disable `ReadRange` by modifying these lines
https://github.com/gigforks/minio/blob/2465039f0f2718869b4a355956f1b5ed898573d8/cmd/gateway/zerostor/zerostor.go#L75-L82

**Comment by zaibon** [comment]
https://github.com/zero-os/0-stor/commit/6f3e9fa2d2b714613eaacca7841ca4ee9a588c2a

**Comment by zaibon** [comment]
I did a lot of test yesterday here is what I found:
I stripped down the configuration to the most simple thing:
```yaml
namespace: miniotest
password: ''
datastor: # required
  shards: # required
    - 192.168.58.96:9900
    - 192.168.58.96:9901
  pipeline:
    block_size: 1048576
    compression: # optional, snappy by default
      mode: '' # disable compression
    encryption: # optional, disabled by default
      private_key: '' # disable encryption
    distribution:
      data_shards: 2
```
So minio is deployed on the same node as the zdbs, not compression not encryption, just simple replication.
Then I wrote a small test script, that just create a bucket, write a file, download it back and compare:
```shell
#!/bin/bash
set -x

mc mb test/zaibon
mc cp blob test/zaibon
mc ls test/zaibon
rm blob2
mc cat test/zaibon/blob > blob2
diff blob blob2
```

It tested this script with different block size, the script works with up to 64K block size. Above that, the download doesn't work and I get an empty file.

We double check the networking of the containers deployed in 0-os, everything can reach everything.
That was already confirmed just by the fact that the write never fails
