### ISSUE TITLE
in replication mode fails to read when one of the shards is down

### ISSUE THREAD

**Issue by zaibon** [gigforks/minio#29]
```yaml
namespace: miniotest
password: None
datastor: # required
  shards: # required
    - localhost:9900
    - localhost:9901
  pipeline:
    block_size: 1049000
    compression: # optional, snappy by default
      type: snappy # snappy is the default, other options: lz4, gzip
      mode: default # default is the default, other options: best_speed, best_compression
    encryption: # optional, disabled by default
      type: aes # aes is the default and only standard option
      private_key: ab345678901234567890123456789012
    distribution:
      DataShardCount: 2
```
This config enable replication, each file is written on both data shards

```shell
mc cp blob local/zaibon
# shut down on of the data shards
mc cat local/zaibon/blob > down
mc: <ERROR> Unable to read from `local/zaibon/blob`. unexpected EOF
```
minio debug:
```
ListObjects bucket:zaibon, prefix:blob, marker:, delimiter:/, maxKeys:1000
GetObject bucket:zaibon, object:blob, offset:0, length:5242880, etag:
	GetObject using zerostor ReadRange

Trace: 1: cmd/object-handlers.go:172:cmd.objectAPIHandlers.GetObjectHandler()
       2: cmd/api-router.go:59:cmd.(objectAPIHandlers).GetObjectHandler-fm()
       3: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
       4: vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
       5: cmd/generic-handlers.go:563:cmd.pathValidityHandler.ServeHTTP()
       6: cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
       7: :0:()
       8: cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
       9: :0:()
      10: cmd/generic-handlers.go:219:cmd.redirectHandler.ServeHTTP()
      11: :0:()
      12: cmd/generic-handlers.go:277:cmd.minioReservedBucketHandler.ServeHTTP()
      13: :0:()
      14: cmd/generic-handlers.go:246:cmd.cacheControlHandler.ServeHTTP()
      15: :0:()
      16: cmd/generic-handlers.go:347:cmd.timeValidityHandler.ServeHTTP()
      17: :0:()
      18: vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      19: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      20: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      21: cmd/generic-handlers.go:453:cmd.resourceHandler.ServeHTTP()
      22: cmd/auth-handler.go:245:cmd.authHandler.ServeHTTP()
      23: :0:()
      24: pkg/http/server.go:111:http.(*Server).Start.func1()
      25: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      26: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      27: net/http/server.go:2694:http.serverHandler.ServeHTTP()
      28: net/http/server.go:1830:http.(*conn).serve()
[2018-03-16T11:30:33.191129947Z] [ERROR] Unable to write to client. (dial tcp [::1]:9900: connect: connection refused)
```

I though that when replication is used, we could always read even if one of the shards was done since we have the same data replicated on all shards. So I don't think I should get an error here
