### ISSUE TITLE
Failure when writing multipart to several zdbs

### ISSUE THREAD

**Issue by grimpy** [gigforks/minio#70]
## Expected Behavior
Able to write data with minio client
## Current Behavior
Error happens when writing to minio with minio client
Using the following script i got errors writing to a minio setup to work against 4 zdbs
https://github.com/gigforks/minio/pull/66/files

Errors:
https://gist.github.com/grimpy/027fb3ef479d199411ac37b75c5d1dc8
Config used:
```
namespace: minio                                                                         
password: rooter                                                                         
datastor: # required                                                                     
  shards: # required                                                                     
    - 10.10.100.131:9910                                                                 
    - 10.10.100.131:9911                                                                 
    - 10.10.100.132:9910                                                                 
    - 10.10.100.132:9911                                                                 
  pipeline:                                                                              
    block_size: 1048576                                                                  
    compression: # optional, snappy by default                                           
      type: snappy # snappy is the default, other options: lz4, gzip                     
      mode: default # default is the default, other options: best_speed, best_compression
    encryption: # optional, disabled by default                                          
      type: aes # aes is the default and only standard option                            
      private_key: c2ym8g9b6sxow5ridf56gb9885wxb10i                                      
    distribution:                                                                        
      data_shards: 4                                                                     
```
